### ISSUE TITLE
[Epic]: Landing Page

### ISSUE THREAD

**Issue by frfernandezdev** [MindStartups/fanclip#22]
## Descripción:

Como **user** quiero poder explorar facilmente que categorías de celebridades puedo contratar, cómo funciona la solicitud de mensajes, la reacción de los clientes antiguos en video, y las reseñas escritas por los clientes anteriores además de un resumen sobre lo que FanClip hace.    

### Criterios de aceptación:
- [ ] La landing page debe permitir enlazar videos en la sección "reacciones de usuarios" y poder revisar todas las reacciones con la ayuda de botones de navegación. 
- [ ] La landing page debe permitir recuperar las reseñas de usuarios a nivel general. 
- [ ] Es necesario una sección en la que se pueda visualizar las categorías de las celebridades. 

### Componentes:
- [ ] #1 
- [ ] #2 
   
### Secciones:
- [ ] #4 
- [ ] Es necesario visualizar  un manual de usuario del "¿Cómo funciona?"  dividido en pasos.
- [ ] Carrusel de imágenes de la reacción de los usuarios, con sus respectivos botones de interacción.  
- [ ] Reseñas recientes
- [ ]  Acerca de FanClip

**Figma**:
https://www.figma.com/file/GaSIQAfThEPQCE3aDurOWc/MVP-FanClip?type=design&node-id=2-2&mode=design&t=n6P5gc1a6OuVp1ds-4
