### ISSUE TITLE
[Epic]: Autentificación

### ISSUE THREAD

**Issue by frfernandezdev** [MindStartups/fanclip#24]
## Descripción:
Como user debo poder autentificarse y registrarse

### Criteria de aceptación:
- Pantallas:
    - [ ] #31 Pantalla de registro con dos opciones de re dirección
    - [ ] #25 Pantalla con el formulario para el registro de usuarios
    - [ ] #26 Pantalla con el formulario para el registro de celebridad 
    - [ ] #32 Pantalla de iniciar sesión con dos opciones de re dirección
    - [ ] #27 Pantalla  con el formulario para iniciar sesión como usuario.
    - [ ] #28 Pantalla con el formulario para iniciar sesión como celebridad.
    - [ ] #29 Pantalla de registro completado para usuarios.
    - [ ] #30 Pantalla de registro completado para celebridades

 #### Figma:
https://www.figma.com/file/GaSIQAfThEPQCE3aDurOWc/MVP-FanClip?type=design&node-id=0-1&mode=design&t=7WmZoJcCz9re5Odn-0
